before_script:
  - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

services:
    - docker:dind
    
build-job:       # This job runs in the build stage, which runs first.
  image: docker:dind
  stage: build
  script:
  #  - docker rmi nextjs-image 2>/dev/null
    - docker rmi $(docker images -q)
    - docker rm $(docker ps -q)
    - docker build -t nextjs-image .
    - docker run -d -p 3003:3000  --name nextjs-container --rm nextjs-image 
    - docker images -a
    - docker ps -a 
    - echo "Compiling the code..."
    - echo "Compile complete."
  tags:
    - docker
  only:
    - deploy
    
deploy-job:      # This job runs in the deploy stage.
  image: docker:dind 
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
  #  - docker rm nextjs-container 2>/dev/null
    - docker images -a
    - docker ps -a 
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  tags:
    - docker
