stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

services:
  - docker:dind

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker build -t nextjs-docker .
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - docker run -p 3000:3000 nextjs-docker
    - echo "Deploying application..."
    - echo "Application successfully deployed."
