stages:          # List of stages for jobs, and their order of execution
  - deploy

services:
    - docker:dind
    
build-job:  
  image: docker:dind   
  stage: deploy
  script:
    #- pm2 start npm --  dev
    - docker build -t nextjs-image .
    - docker run -d -p 3003:3003  --name nextjs-container  nextjs-image 
    - echo "Compiling the code..."
    - echo "Compile complete."
  only:
    - deploy
